CC=cl.exe
LINK=link.exe

TARGET = i8080_tests.exe
SOURCES = i8080_tests.c i8080.c instructions.c
OBJ = i8080_tests.obj i8080.obj instructions.obj

all: $(TARGET)

$(TARGET): $(SOURCES)
	echo Building...
	$(CC) $(SOURCES) /link /out:$(TARGET)

clean:
	del $(OBJ) $(TARGET)